version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # Port cho giao tiếp AMQP
      - '15672:15672' # Port cho RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin # Tên người dùng mặc định
      RABBITMQ_DEFAULT_PASS: password # Mật khẩu mặc định
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Lưu trữ dữ liệu persistent

volumes:
  rabbitmq_data:
